# Generated by Django 5.0.6 on 2025-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
